### PR TITLE
plz

### PR DESCRIPTION
**Pull request by MatiasMarek94**
accept

### CODE REVIEW

**Review by mforberg — APPROVED** [review]
This is very nice.

**Review by SmiteyJonawar — APPROVED** [review]
Kachow

**Review by LangeHenrik — CHANGES_REQUESTED** [review]
We can not merge this pull request. You project should be in a sub-folder, named with your SDU handle (the part before the @ in your sdu email adress. You have placed all your files in the root folder of the repository, and deleted the files that should be there.
It is easy enough to fix, but if it becomes a problem, please contact me after the lecture tomorrow, and I will help you fix it.

**Comment by MatiasMarek94** [comment]
the requested changes have been made, it seams that I can not make a new pull request before this one is accepted by all review members.

**Review by LangeHenrik — APPROVED** [review]

**Pull request merged**
