### PR TITLE
Branch Created with txt file :+1:

### PR DESCRIPTION
**Pull request by SmiteyJonawar**

### CODE REVIEW

**Comment by MatiasMarek94** [comment]
Det kunne du godt have gjort bedre

**Review by MatiasMarek94 — APPROVED** [review]
wow.

**Review by mforberg — APPROVED** [review]
This is also very nice.

**Comment by mforberg** [comment]
You make me want to be a better man.

**Review by LangeHenrik — CHANGES_REQUESTED** [review]
Could you rename your folder from SmiteyJonawar to you SDU handle instead? The part of your SDU email adress that comes before the @

**Pull request closed without merging**
